# Generated by Django 5.2.4 on 2025-07-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_object_alter_article_options_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='object',
        ),
        migrations.RenameModel(
            old_name='Object',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_object', models.BooleanField(default=False, verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
