# Generated by Django 5.2.4 on 2025-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_object_rename_object_tag_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='article', through='articles.Scope', to='articles.tag'),
        ),
    ]
